default_platform(:android)
ENV['FASTLANE_SKIP_CONFIRMATIONS'] = 'true'

platform :android do
  desc "Crie o APK e distribua via Firebase App Distribution"
  lane :distribute do
    gradle(task: "clean assembleRelease") # Compila o APK de release

    firebase_app_distribution(
      app: "1:125919459565:android:27071b69f0e8078f14b4e4", # Substitua pelo ID do app do Firebase
      apk_path: "app/build/outputs/apk/release/app-release.apk", # Caminho do APK gerado
      testers: "weversonluan17@gmail.com, wltech2022@gmail.com", # E-mails dos testadores
      release_notes: "Nova versão do app!"
    )
  end
end
